// FILE: /Users/randymcmillan/COP3331/Assignments/Project//Adjunct.cpp

#include "Adjunct.h"


{
    /* {src_lang=cpp}*/


    // Operations

void Adjunct::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-16--6ac90ac3:1583ac5dd20:-8000:0000000000000AFB begin
{
}
// section -64--88-1-16--6ac90ac3:1583ac5dd20:-8000:0000000000000AFB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

